[project]
site_name = "named_xlsx"
site_url = "https://dfosas.github.io/named_xlsx/"
docs_dir = "docs"
site_dir = "site"
nav = [
    { Overview = "index.md" },
    { API = [
        { Overview = "api/index.md" },
        { "Commandline Interfaces" = "api/cli.md" },
        { Engines = "api/engines.md" },
        { Refresh = "api/refresh.md" },
        { Utilities = "api/utils.md" },
    ] },
]

[project.theme]
variant = "classic"

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "numpy"
